# Generated by Django 3.2.4 on 2021-06-26 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210626_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
