# Generated by Django 3.2.4 on 2021-06-27 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='document',
            new_name='proof',
        ),
    ]
