# Generated by Django 3.2.4 on 2021-06-26 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_loans', '0002_loans_total_amount_to_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='loans',
            name='payBack_periode',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], default='3', max_length=50, null=True),
        ),
    ]
