# Generated by Django 3.2.4 on 2021-06-26 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_loans', '0004_alter_loans_payback_periode'),
    ]

    operations = [
        migrations.AddField(
            model_name='loans',
            name='remaining_amount_to_pay',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='loans',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
    ]
