# Generated by Django 3.2.4 on 2021-07-06 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('money_loans', '0005_auto_20210626_0741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loans',
            old_name='payBack_periode',
            new_name='payBack_periods',
        ),
    ]
